### ISSUE TITLE
hulk fails for bigger projects

### ISSUE THREAD

**Issue by sthiessen23** [GRaViTY-Tool/gravity-tool#12]
I tested 2 bigger projects for hulk (gson and jsonPath) and they both fail during this method call `final TypeGraph pg = converter.getPG();` in the HulkAPI detect method.

The error is thrown in the class DataFlowVisitor in a handle-method.

Message is :

> org.eclipse.emf.common.util.BasicEList$BasicIndexOutOfBoundsException: index=0, size=0
> 	at org.eclipse.emf.common.util.BasicEList.get(BasicEList.java:346)
> 	at org.gravity.modisco.processing.fwd.dataflow.DataFlowVisitor.handle(DataFlowVisitor.java:983)
> ...

Before the error is thrown there are also a lot of messages like this in the log:

org.gravity.modisco.processing.fwd.AccessPreprocessing  - Cannot process access as it isn't defined in a member
ERROR org.gravity.modisco.processing.fwd.AccessPreprocessing  - Skipped unresolved method: 

I also noticed that the TravisCI build recently fails with a modisco error, so it seems something changed there.

I also tested with a hello World project (just 1 class) and that worked

**Comment by SvenPeldszus** [comment]
Caught the exceptions to create a program model.

While in gson accesses to values of Java-annotations have not been included in the MoDisco model JsonPath had missing libraries. Both might reduce the quality of the model but are not critical.

The issue with JsonPath might be fixed with a better grade importer as part of GRaViTY.
